# Form implementation generated from reading ui file '/Users/michaltalaga/Desktop/ZAWODOWE/DESKTOPOWE/PYTHON/egzamin1/muzyka.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 324)
        MainWindow.setStyleSheet("background: #2E8B57\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.previous_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.previous_button.setGeometry(QtCore.QRect(20, 120, 10, 70))
        self.previous_button.setText("")
        self.previous_button.setStyleSheet("\n"
"                background-image: url(\'obraz3.png\')\n"
"        ")
        self.previous_button.setObjectName("previous_button")
        self.next_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_button.setGeometry(QtCore.QRect(840, 120, 10, 70))
        self.next_button.setText("")
        self.next_button.setStyleSheet("\n"
"                background-image: url(\'obraz2.png\')\n"
"        ")
        self.next_button.setObjectName("next_button")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 201, 201))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("/Users/michaltalaga/Desktop/ZAWODOWE/DESKTOPOWE/PYTHON/egzamin1/obraz.png"))
        self.label_3.setObjectName("label_3")
        self.artist_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.artist_label.setGeometry(QtCore.QRect(370, 10, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.artist_label.setFont(font)
        self.artist_label.setStyleSheet("color: white")
        self.artist_label.setObjectName("artist_label")
        self.album_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.album_label.setGeometry(QtCore.QRect(370, 80, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(True)
        self.album_label.setFont(font)
        self.album_label.setStyleSheet("color: white\n"
"")
        self.album_label.setObjectName("album_label")
        self.songs_number_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.songs_number_label.setGeometry(QtCore.QRect(370, 160, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.songs_number_label.setFont(font)
        self.songs_number_label.setStyleSheet("color: #61D918\n"
"")
        self.songs_number_label.setObjectName("songs_number_label")
        self.year_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.year_label.setGeometry(QtCore.QRect(550, 160, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.year_label.setFont(font)
        self.year_label.setStyleSheet("color: #61D918")
        self.year_label.setObjectName("year_label")
        self.download_number_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.download_number_label.setGeometry(QtCore.QRect(140, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.download_number_label.setFont(font)
        self.download_number_label.setStyleSheet("color: #61D918")
        self.download_number_label.setObjectName("download_number_label")
        self.download_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.download_button.setGeometry(QtCore.QRect(340, 250, 100, 32))
        font = QtGui.QFont()
        font.setBold(True)
        self.download_button.setFont(font)
        self.download_button.setStyleSheet("background: #61D918;\n"
"color: black;")
        self.download_button.setObjectName("download_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MojeDżwięki, Wykonał: 05251202599"))
        self.artist_label.setText(_translate("MainWindow", "Wykonawca"))
        self.album_label.setText(_translate("MainWindow", "Album"))
        self.songs_number_label.setText(_translate("MainWindow", "Ilość utworów"))
        self.year_label.setText(_translate("MainWindow", "Rok"))
        self.download_number_label.setText(_translate("MainWindow", "Ilość odtworzeń"))
        self.download_button.setText(_translate("MainWindow", "Pobierz"))
